# 指定运行端口
server:
  port: 8002

# 服务名
spring:
  application:
    name: core-service

#指定注册中心
eureka:
  client:
    # 注册到注册中心
    register-with-eureka: true
    # 注册中心服务地址
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/